# Decision Trees
You should build a machine learning pipeline using a decision tree model. In particular, you should do the following:
- Load the `mnist` dataset using [Pandas](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html). You can find this dataset in the datasets folder.
- Split the dataset into training and test sets using [Scikit-Learn](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html). 
- Train and test a decision tree model using [Scikit-Learn](https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html).
- Check the documentation to identify the most important hyperparameters, attributes, and methods of the model. Use them in practice.

In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [14]:
df = pd.read_csv("../../datasets/mnist.csv")
df = df.set_index("id")
df.head()

class  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
id                                                                             
31953      5       0       0       0       0       0       0       0       0   
34452      8       0       0       0       0       0       0       0       0   
60897      5       0       0       0       0       0       0       0       0   
36953      0       0       0       0       0       0       0       0       0   
1981       3       0       0       0       0       0       0       0       0   

       pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  \
id             ...                                                     
31953       0  ...         0         0         0         0         0   
34452       0  ...         0         0         0         0         0   
60897       0  ...         0         0         0         0         0   
36953       0  ...         0         0         0         0         0   
1981        0  ...         0         0         0         0         0   

       pixel780  pixel781  pixel782  pixel783  pixel784  
id                                                       
31953         0         0         0         0         0  
34452         0         0         0         0         0  
60897         0         0         0         0         0  
36953         0         0         0         0         0  
1981          0         0         0         0         0  

[5 rows x 785 columns]

In [15]:
df.shape

(4000, 785)

In [16]:
X = df.drop('class', axis=1)
y = df['class'] 

In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.10)

In [29]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)

DecisionTreeClassifier()

In [31]:
y_pred = classifier.predict(X_test)

In [32]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[39  0  0  1  0  4  1  0  1  0]
 [ 0 41  0  1  0  1  0  0  3  0]
 [ 0  0 25  2  1  3  2  0  0  0]
 [ 0  0  1 38  0  1  0  0  3  1]
 [ 0  0  0  0 30  1  0  0  0  0]
 [ 1  0  1  5  0 25  1  0  1  1]
 [ 2  0  0  0  1  3 30  0  0  2]
 [ 0  0  1  4  0  0  0 47  0  4]
 [ 0  3  4  0  2  1  2  0 29  1]
 [ 0  0  0  0  3  0  0  2  2 22]]
              precision    recall  f1-score   support

           0       0.93      0.85      0.89        46
           1       0.93      0.89      0.91        46
           2       0.78      0.76      0.77        33
           3       0.75      0.86      0.80        44
           4       0.81      0.97      0.88        31
           5       0.64      0.71      0.68        35
           6       0.83      0.79      0.81        38
           7       0.96      0.84      0.90        56
           8       0.74      0.69      0.72        42
           9       0.71      0.76      0.73        29

    accuracy                           0.81       400
   macro avg       

In [34]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))


Mean Absolute Error: 0.675
Mean Squared Error: 3.165
Root Mean Squared Error: 1.7790446874657195
